name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当main分支有推送时触发
  workflow_dispatch:  # 允许手动触发工作流

# 设置GITHUB_TOKEN的权限
permissions:
  contents: write  # 给予写入仓库内容的权限

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to gh branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh  # 部署到gh分支
          folder: dist  # Vite构建输出目录
          clean: true  # 清除旧文件 